run:
  build-tags:
    - integration
  timeout: 10m
  skip-dirs:
    - example
linters:
  disable:
    - execinquery
  enable:
    - dogsled
    - dupl
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - whitespace
linters-settings:
  gosec:
    excludes:
      # duplicates errcheck
      - G104
      # performance issue: see https://github.com/golangci/golangci-lint/issues/4039
      # and https://github.com/securego/gosec/issues/1007
      - G602
issues:
  exclude-use-default: true
  exclude-rules:
    - linters:
        - dupl
        - unparam
        - gosec
        - dogsled
      path: _test\.go

    # We need to pass nil Context in order to test nil contexts.
    - linters: [ staticcheck ]
      text: 'SA1012: do not pass a nil Context'
      path: _test\.go

    # This is adapted from golangci-lint's default exclusions. It disables linting for error checks on
    # os.RemoveAll and any function ending in "Close".
    - linters: [ errcheck ]
      text: Error return value of .(.*Close|os\.Remove(All)?). is not checked
