repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
       - id: trailing-whitespace
       - id: end-of-file-fixer
       - id: check-yaml
       - id: check-added-large-files
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
        args: [./..]
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: golangci-lint
        args: ["--config=./.golanagci.yml"]
      - id: go-critic
      - id: go-mod-tidy
      - id: no-go-testing
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.13.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
  - repo: local
    hooks:
      - id: test.sh
        name: test.sh
        entry: script/test.sh
        language: script
        types: [bash]
        pass_filenames: false
        args: [-race -covermode atomic ./... ]
