name: Linter

on: [pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.x
          cache-dependeny-path: "**/go.sum"
      - run: script/lint.sh
        env:
            GITHUB_TOKEN: ${{ github.token }}
